#!/usr/bin/env bash
# Bump Flutter dashboard build number (pubspec + build_info.dart).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBSPEC="${ROOT}/apps/dashboard/pubspec.yaml"
OUT="${ROOT}/apps/dashboard/lib/config/build_info.dart"

line="$(grep '^version:' "$PUBSPEC")"
if [[ "$line" =~ version:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+) ]]; then
  ver="${BASH_REMATCH[1]}"
  build=$((BASH_REMATCH[2] + 1))
elif [[ "$line" =~ version:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+) ]]; then
  ver="${BASH_REMATCH[1]}"
  build=1
else
  echo "Could not parse version in $PUBSPEC (expected semver or semver+build)"
  exit 1
fi

if [[ "$(uname -s)" == Darwin ]]; then
  sed -i '' "s/^version:.*/version: ${ver}+${build}/" "$PUBSPEC"
else
  sed -i "s/^version:.*/version: ${ver}+${build}/" "$PUBSPEC"
fi

cat >"$OUT" <<EOF
// Generated by scripts/bump-build.sh — do not edit by hand.
const appVersion = '$ver';
const buildNumber = $build;

String get versionLabel => 'v\$appVersion+\$buildNumber';
EOF

echo "==> Dashboard build ${ver}+${build}"
